<?php
define ('QCUBED_PROJECT_MODELCONNECTOR_DIR', QCUBED_PROJECT_INCLUDES_DIR . '/connector' );
define ('QCUBED_PROJECT_MODELCONNECTOR_GEN_DIR', QCUBED_PROJECT_GEN_DIR . '/connector_base' );
define ('QCUBED_PROJECT_DIALOG_DIR', QCUBED_PROJECT_INCLUDES_DIR . '/dialog' );
define ('QCUBED_PROJECT_DIALOG_GEN_DIR', QCUBED_PROJECT_GEN_DIR . '/dialog_base' );
define ('QCUBED_PROJECT_PANEL_DIR', QCUBED_PROJECT_INCLUDES_DIR . '/panel' );
define ('QCUBED_PROJECT_PANEL_GEN_DIR', QCUBED_PROJECT_GEN_DIR . '/panel_base' );
